// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "cellauto_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// cpp_init_address
void cpp_init_address(Mats mats, int nrow, int ncol);
RcppExport SEXP cellauto_cpp_init_address(SEXP matsSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Mats >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    cpp_init_address(mats, nrow, ncol);
    return R_NilValue;
END_RCPP
}
// cpp_update
void cpp_update(const IntegerVector changes, Mats mats, const bool lives);
RcppExport SEXP cellauto_cpp_update(SEXP changesSEXP, SEXP matsSEXP, SEXP livesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector >::type changes(changesSEXP);
    Rcpp::traits::input_parameter< Mats >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< const bool >::type lives(livesSEXP);
    cpp_update(changes, mats, lives);
    return R_NilValue;
END_RCPP
}
// cpp_step
size_t cpp_step(IntegerVector born_at, IntegerVector lives_at, double grow, double decay, Mats mats, List counts);
RcppExport SEXP cellauto_cpp_step(SEXP born_atSEXP, SEXP lives_atSEXP, SEXP growSEXP, SEXP decaySEXP, SEXP matsSEXP, SEXP countsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type born_at(born_atSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lives_at(lives_atSEXP);
    Rcpp::traits::input_parameter< double >::type grow(growSEXP);
    Rcpp::traits::input_parameter< double >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< Mats >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< List >::type counts(countsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_step(born_at, lives_at, grow, decay, mats, counts));
    return rcpp_result_gen;
END_RCPP
}
