# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_init_address <- function(mats, nrow, ncol) {
    invisible(.Call('cellauto_cpp_init_address', PACKAGE = 'cellauto', mats, nrow, ncol))
}

cpp_update <- function(changes, mats, lives = TRUE) {
    invisible(.Call('cellauto_cpp_update', PACKAGE = 'cellauto', changes, mats, lives))
}

cpp_step <- function(born_at, lives_at, grow, decay, mats, counts) {
    .Call('cellauto_cpp_step', PACKAGE = 'cellauto', born_at, lives_at, grow, decay, mats, counts)
}

